name:                go-to-assignment
version:             0.1.0.0
github:              "madgen/go-to-assignment"
license:             BSD3
author:              "Mistral Contrastin"
maintainer:          "madgenhetic@gmail.com"
copyright:           "Copyright (c) 2023 Mistral Contrastin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madgen/go-to-assignment#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- transformers
- strict
- lsp
  
build-tools:
- alex
- happy

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  go-to-assignment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-to-assignment

tests:
  go-to-def-assignment:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-to-def-ssa
    - filepath
    - directory
    - Diff
